#!/bin/bash
set -eu

printf "\nBuilding Elmwordle...\n\n"

rm -rf build

mkdir build

cp -r   docs/*    build/

time npx elm make src/Main.elm --output=build/elm.js --debug
time npx terser build/elm.js  --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=build/elm.js 

printf "\nFiles to release Elmwordle in production are available in ./build/\n\n"
